name: Render Keep‑Alive
on:
  schedule:
    - cron:  '*/14 * * * *'  # 14分ごとに実行

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -fsSL https://<SERVICE>.onrender.com/_stcore/health || true